# Configure Proxmox provider
provider "proxmox" {
  pm_api_url          = var.proxmox_api_url
  pm_api_token_id     = var.proxmox_api_token_id
  pm_api_token_secret = var.proxmox_api_token_secret
  pm_tls_insecure     = true
  pm_debug            = false
  pm_log_enable       = true
  pm_log_file         = "terraform-proxmox.log"
  pm_log_levels = {
    _default    = "debug"
    _capturelog = ""
  }
}

# Generate SSH key pair if not exists
resource "tls_private_key" "ssh_key" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "local_file" "private_key" {
  content         = tls_private_key.ssh_key.private_key_openssh
  filename        = pathexpand("${path.module}/ssh_keys/id_rsa")
  file_permission = "0600"
}

resource "local_file" "public_key" {
  content         = tls_private_key.ssh_key.public_key_openssh
  filename        = pathexpand("${path.module}/ssh_keys/id_rsa.pub")
  file_permission = "0644"
}

# Create directory for Ansible inventory
resource "local_file" "ansible_inventory_header" {
  filename = "../ansible/inventories/terraform_generated.ini"
  content = <<-EOT
    # Auto-generated by Terraform
    # Generated at: ${timestamp()}
    
    [webservers]
    
  EOT
}

# Create VMs using module
module "web_servers" {
  source = "./modules/vm"
  
  vm_count      = var.vm_count
  vm_name_prefix = "${var.vm_name_prefix}-${var.environment}"
  target_node   = var.proxmox_target_node
  template_name = var.vm_template_name
  
  cpu_cores  = var.vm_cpu_cores
  memory     = var.vm_memory
  disk_size  = var.vm_disk_size
  disk_storage = var.vm_disk_storage
  
  network_bridge = var.network_bridge
  ssh_user       = var.ssh_user
  ssh_public_key = coalesce(var.ssh_public_key, tls_private_key.ssh_key.public_key_openssh)
  ssh_private_key_path = pathexpand(var.ssh_private_key_path)
  
  ip_addresses = var.vm_ip_addresses
  gateway      = var.vm_gateway
  nameservers  = var.vm_nameservers
  domain       = "local"
  
  ansible_inventory_path = "../ansible/inventories/terraform_generated.ini"
  tags = merge(var.tags, {
    Environment = var.environment
    Role        = "webserver"
  })
}

# Generate Ansible variables file
resource "local_file" "ansible_vars" {
  filename = "../ansible/group_vars/terraform_generated.yml"
  content = yamlencode({
    terraform_generated = true
    vm_count = var.vm_count
    vm_ip_addresses = module.web_servers.vm_ip_addresses
    vm_names = module.web_servers.vm_names
    environment = var.environment
    web_server_port = var.web_server_port
    ssh_user = var.ssh_user
  })
}

# Generate README with connection info
resource "local_file" "deployment_readme" {
  filename = "DEPLOYMENT.md"
  content = <<-EOT
    # Deployment Information
    
    ## Environment: ${var.environment}
    ## Created: ${timestamp()}
    
    ## Virtual Machines
    %{ for i, vm in module.web_servers.vm_names ~}
    ### VM ${i + 1}: ${vm}
    - ID: ${module.web_servers.vm_ids[i]}
    - IP Address: ${module.web_servers.vm_ip_addresses[i]}
    - SSH: ssh -i ssh_keys/id_rsa ${var.ssh_user}@${module.web_servers.vm_ip_addresses[i]}
    
    %{ endfor ~}
    
    ## Ansible Inventory
    Inventory file generated at: ansible/inventories/terraform_generated.ini
    
    ## Next Steps
    1. Configure Ansible: cd ../ansible
    2. Run playbook: ansible-playbook -i inventories/terraform_generated.ini site.yml
    3. Verify deployment: curl http://${module.web_servers.vm_ip_addresses[0]}:${var.web_server_port}
    
    ## SSH Keys
    - Private key: terraform/ssh_keys/id_rsa
    - Public key: terraform/ssh_keys/id_rsa.pub
    
    ## Security Notes
    - Change default passwords
    - Configure firewall rules
    - Set up monitoring
  EOT
}
